name: pca_sales_demo
version: "1.0.0"

profile: pca_sales_demo

model-paths: ["models"]
seed-paths: ["seeds"]

clean-targets:
  - target
  - dbt_packages

seeds:
  pca_sales_demo:
    +schema: marts

models:
  pca_sales_demo:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
